<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>LabApp</RootNamespace>
    <NoWarn>CS8622</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <!-- Локальная база данных -->
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.8" />
    <!-- Графики (более новая версия — в rc2 была известная проблема с пустым графиком на .NET 8) -->
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc5.4" />
  </ItemGroup>

</Project>
